In [10]:
#Merge (Combine tables based on a common column)
import pandas as pd
df = pd.DataFrame([[1,"ram"],[2,"sam"],[3,"var"]], columns=["id","name"])
print(df.to_string(index=False))

 id name
  1  ram
  2  sam
  3  var

In [11]:
df2={
    'costmer_id':[101,102,103,104],
    "id":[1,2,4,5],
    "amount":[10000,2000,3000,4000]
    }
print(pd.DataFrame(df2).to_string(index=False))

 costmer_id  id  amount
        101   1   10000
        102   2    2000
        103   4    3000
        104   5    4000

In [12]:
#Basic Merge Syntax
df2_df = pd.DataFrame(df2) # Convert the dictionary df2 to a DataFrame
pd.merge(df, df2_df, on="id", how="inner") # Merge on the common 'id' column

   id name  costmer_id  amount
0   1  ram         101   10000
1   2  sam         102    2000

In [13]:
# 1 Inner merge
pd.merge(df, df2_df, on="id", how="inner") # Merge on the common 'id' column

   id name  costmer_id  amount
0   1  ram         101   10000
1   2  sam         102    2000

In [14]:
# 2 Left Merge
pd.merge(df, df2_df, on="id", how="left")

   id name  costmer_id   amount
0   1  ram       101.0  10000.0
1   2  sam       102.0   2000.0
2   3  var         NaN      NaN

In [15]:
#RightMerge
pd.merge(df, df2_df, on="id", how="right")

   id name  costmer_id  amount
0   1  ram         101   10000
1   2  sam         102    2000
2   4  NaN         103    3000
3   5  NaN         104    4000

In [16]:
#outerMerge
pd.merge(df, df2_df, on="id", how="outer")

   id name  costmer_id   amount
0   1  ram       101.0  10000.0
1   2  sam       102.0   2000.0
2   3  var         NaN      NaN
3   4  NaN       103.0   3000.0
4   5  NaN       104.0   4000.0

In [19]:
#2. JOIN "Merge using index instead of column"
df.join(df2_df.set_index('id'),on='id',lsuffix='_left',rsuffix='_right')

   id name  costmer_id   amount
0   1  ram       101.0  10000.0
1   2  sam       102.0   2000.0
2   3  var         NaN      NaN

In [20]:
#3. CONCAT "Just attach data"
pd.concat([df,df2_df],axis=1)

    id name  costmer_id  id  amount
0  1.0  ram         101   1   10000
1  2.0  sam         102   2    2000
2  3.0  var         103   4    3000
3  NaN  NaN         104   5    4000

In [21]:
import pandas as pd

customers = pd.DataFrame({
    "id": [1,2,3],
    "name": ["A", "B", "C"]
})

orders = pd.DataFrame({
    "id": [1,2,4],
    "amount": [100,200,300]
})

# Try all joins
print(pd.merge(customers, orders, on="id", how="inner"))
print(pd.merge(customers, orders, on="id", how="left"))
print(pd.concat([customers, orders], axis=1))

   id name  amount
0   1    A     100
1   2    B     200
   id name  amount
0   1    A   100.0
1   2    B   200.0
2   3    C     NaN
   id name  id  amount
0   1    A   1     100
1   2    B   2     200
2   3    C   4     300